In [ ]:
import pandas as pd

In [ ]:
documentA = 'the man went out for a walk'
documentB = 'the children sat around the fire'

In [ ]:
bagOfWordsA = documentA.split()
bagOfWordsB = documentB.split()

In [ ]:
bagOfWordsA

['the', 'man', 'went', 'out', 'for', 'a', 'walk']

In [ ]:
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))
uniqueWords

{'a',
 'around',
 'children',
 'fire',
 'for',
 'man',
 'out',
 'sat',
 'the',
 'walk',
 'went'}

In [ ]:
print(dict(zip(uniqueWords, [0] * len(uniqueWords))))

{'fire': 0, 'the': 0, 'walk': 0, 'sat': 0, 'for': 0, 'around': 0, 'a': 0, 'went': 0, 'out': 0, 'children': 0, 'man': 0}

In [ ]:
numOfWordsA = dict.fromkeys(uniqueWords, 0)
numOfWordsA

{'fire': 0,
 'the': 0,
 'walk': 0,
 'sat': 0,
 'for': 0,
 'around': 0,
 'a': 0,
 'went': 0,
 'out': 0,
 'children': 0,
 'man': 0}

In [ ]:
for word in bagOfWordsA:
    numOfWordsA[word] += 1
numOfWordsA

{'fire': 0,
 'the': 1,
 'walk': 1,
 'sat': 0,
 'for': 1,
 'around': 0,
 'a': 1,
 'went': 1,
 'out': 1,
 'children': 0,
 'man': 1}

In [ ]:
numOfWordsB = dict.fromkeys(uniqueWords, 0)

for word in bagOfWordsB:
    numOfWordsB[word] += 1

numOfWordsB

{'fire': 1,
 'the': 2,
 'walk': 0,
 'sat': 1,
 'for': 0,
 'around': 1,
 'a': 0,
 'went': 0,
 'out': 0,
 'children': 1,
 'man': 0}

In [ ]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

In [ ]:
tfA = computeTF(numOfWordsA,bagOfWordsA)
tfA

{'fire': 0.0,
 'the': 0.14285714285714285,
 'walk': 0.14285714285714285,
 'sat': 0.0,
 'for': 0.14285714285714285,
 'around': 0.0,
 'a': 0.14285714285714285,
 'went': 0.14285714285714285,
 'out': 0.14285714285714285,
 'children': 0.0,
 'man': 0.14285714285714285}

In [ ]:
tfB = computeTF(numOfWordsB, bagOfWordsB)
tfB

{'fire': 0.16666666666666666,
 'the': 0.3333333333333333,
 'walk': 0.0,
 'sat': 0.16666666666666666,
 'for': 0.0,
 'around': 0.16666666666666666,
 'a': 0.0,
 'went': 0.0,
 'out': 0.0,
 'children': 0.16666666666666666,
 'man': 0.0}

In [ ]:
def computeIDF(documents):
    import math
    N = len(documents)

    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1

    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [ ]:
idfs = computeIDF([numOfWordsA, numOfWordsB])
idfs

{'fire': 0.6931471805599453,
 'the': 0.0,
 'walk': 0.6931471805599453,
 'sat': 0.6931471805599453,
 'for': 0.6931471805599453,
 'around': 0.6931471805599453,
 'a': 0.6931471805599453,
 'went': 0.6931471805599453,
 'out': 0.6931471805599453,
 'children': 0.6931471805599453,
 'man': 0.6931471805599453}

In [ ]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [ ]:
tfidfA = computeTFIDF(tfA, idfs)
tfidfA

{'fire': 0.0,
 'the': 0.0,
 'walk': 0.09902102579427789,
 'sat': 0.0,
 'for': 0.09902102579427789,
 'around': 0.0,
 'a': 0.09902102579427789,
 'went': 0.09902102579427789,
 'out': 0.09902102579427789,
 'children': 0.0,
 'man': 0.09902102579427789}

In [ ]:
tfidfB = computeTFIDF(tfB, idfs)
tfidfB

{'fire': 0.11552453009332421,
 'the': 0.0,
 'walk': 0.0,
 'sat': 0.11552453009332421,
 'for': 0.0,
 'around': 0.11552453009332421,
 'a': 0.0,
 'went': 0.0,
 'out': 0.0,
 'children': 0.11552453009332421,
 'man': 0.0}

In [ ]:
df = pd.DataFrame([tfidfA, tfidfB])
df.head()

,fire,the,walk,sat,for,around,a,went,out,children,man
0,0.000000,0.0,0.099021,0.000000,0.099021,0.000000,0.099021,0.099021,0.099021,0.000000,0.099021
1,0.115525,0.0,0.000000,0.115525,0.000000,0.115525,0.000000,0.000000,0.000000,0.115525,0.000000

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([documentA, documentB])
print(vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (2, 10)>
  Coords	Values
  (0, 7)	0.3032160644503863
  (0, 4)	0.42615959880289433
  (0, 9)	0.42615959880289433
  (0, 5)	0.42615959880289433
  (0, 3)	0.42615959880289433
  (0, 8)	0.42615959880289433
  (1, 7)	0.5797386715376657
  (1, 1)	0.40740123733358447
  (1, 6)	0.40740123733358447
  (1, 0)	0.40740123733358447
  (1, 2)	0.40740123733358447

In [ ]:
print(vectorizer.vocabulary_)

{'the': 7, 'man': 4, 'went': 9, 'out': 5, 'for': 3, 'walk': 8, 'children': 1, 'sat': 6, 'around': 0, 'fire': 2}

In [ ]:
feature_names = vectorizer.get_feature_names_out()
feature_names

array(['around', 'children', 'fire', 'for', 'man', 'out', 'sat', 'the',
       'walk', 'went'], dtype=object)

In [ ]:
dense = vectors.todense()
dense

matrix([[0.        , 0.        , 0.        , 0.4261596 , 0.4261596 ,
         0.4261596 , 0.        , 0.30321606, 0.4261596 , 0.4261596 ],
        [0.40740124, 0.40740124, 0.40740124, 0.        , 0.        ,
         0.        , 0.40740124, 0.57973867, 0.        , 0.        ]])

In [ ]:
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)
df.head()

,around,children,fire,for,man,out,sat,the,walk,went
0,0.000000,0.000000,0.000000,0.42616,0.42616,0.42616,0.000000,0.303216,0.42616,0.42616
1,0.407401,0.407401,0.407401,0.00000,0.00000,0.00000,0.407401,0.579739,0.00000,0.00000

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

docs = [
    "I love NLP",
    "I love Python",
    "Python loves AI"
]

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(docs)

df = pd.DataFrame.sparse.from_spmatrix(
    X,
    columns=vectorizer.get_feature_names_out()
)

print(df)

         ai      love     loves       nlp    python
0         0  0.605349         0  0.795961         0
1         0  0.707107         0         0  0.707107
2  0.622766         0  0.622766         0   0.47363

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer



data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Basics_of_NLP/Code_Section_03/Questions.csv', sep=',')
data.head()

,Unnamed: 0,Id,OwnerUserId,CreationDate,Score,Title,Body
0,0,469,147.0,2008-08-02T15:11:16Z,21,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...
1,1,502,147.0,2008-08-02T17:01:58Z,27,Get a preview JPEG of a PDF on Windows?,<p>I have a cross-platform (Python) applicatio...
2,2,535,154.0,2008-08-02T18:43:54Z,40,Continuous Integration System for a Python Cod...,<p>I'm starting work on a hobby project with a...
3,3,594,116.0,2008-08-03T01:15:08Z,25,cx_Oracle: How do I iterate over a result set?,<p>There are several ways to iterate over a re...
4,4,683,199.0,2008-08-03T13:19:16Z,28,Using 'in' to match an attribute of Python obj...,<p>I don't remember whether I was dreaming or ...

In [ ]:
X = data['Title']
y = data['Score']

VecModel = TfidfVectorizer()
X_Vec = VecModel.fit_transform(X)
# X_Vec=pd.DataFrame(X_Vec.toarray(),columns=VecModel.get_feature_names_out())
X_Vec = pd.DataFrame.sparse.from_spmatrix(X_Vec,columns=VecModel.get_feature_names_out())

print(f'The new shape for X is {X_Vec.shape}')
X_Vec.head()

The new shape for X is (10000, 6870)

,000,00011110,000z,008,009,04,0400,0b11110,0b5,0d,...,zodb,zombies,zone,zoom,zoomable,zope,zopeinterface,zpt,zsh,zsi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
for i in range(5) :
    print(sorted(list(X_Vec.iloc[i,:]),reverse = True)[:20])
    print('--------------------------------------------------')

[np.float64(0.4221782221761511), np.float64(0.37163959050374423), np.float64(0.3295518435927668), np.float64(0.3266636712171713), np.float64(0.30359365145377626), np.float64(0.2842793386944201), np.float64(0.2771371325025096), np.float64(0.26150590454279876), np.float64(0.186454489818273), np.float64(0.18597326273423465), np.float64(0.17584122839792518), np.float64(0.14999446597627897), np.float64(0.12187283198225854), np.float64(0.11197776573544509), 0, 0, 0, 0, 0, 0]
--------------------------------------------------
[np.float64(0.5426412233100997), np.float64(0.5289190014000659), np.float64(0.4187346787909365), np.float64(0.2942839268145828), np.float64(0.27016796115062247), np.float64(0.2329935255908615), np.float64(0.19122427073824194), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
--------------------------------------------------
[np.float64(0.5645125193070204), np.float64(0.5215694064886434), np.float64(0.4786262936702665), np.float64(0.3573365447207418), np.float64(0.20580239279118884), np.float64(0.10081572147562867), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
--------------------------------------------------
[np.float64(0.5090625627208644), np.float64(0.45228021334724877), np.float64(0.45228021334724877), np.float64(0.3752194639691171), np.float64(0.33991401883074684), np.float64(0.22478750070301515), np.float64(0.15773369219653524), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
--------------------------------------------------
[np.float64(0.49545501901989014), np.float64(0.4017251355893547), np.float64(0.3767557017869033), np.float64(0.3688488495096409), np.float64(0.35419360075396095), np.float64(0.2623900054302421), np.float64(0.22779365299689125), np.float64(0.19507232588073126), np.float64(0.14311257279773454), np.float64(0.10208288800026773), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
--------------------------------------------------

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_Vec, y, test_size=0.25, random_state=42)

In [ ]:
import pandas as pd

In [ ]:
documentA = 'ذهب محمد الي الجامعة ليدرس الفيزياء و الكيمياء'
documentB = 'ذاكرت مني الرياضيات و الفيزياء في الجامعة'

In [ ]:
bagOfWordsA = documentA.split(' ')
bagOfWordsB = documentB.split(' ')

In [ ]:
uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))
uniqueWords

{'الجامعة',
 'الرياضيات',
 'الفيزياء',
 'الكيمياء',
 'الي',
 'ذاكرت',
 'ذهب',
 'في',
 'ليدرس',
 'محمد',
 'مني',
 'و'}

In [ ]:
numOfWordsA = dict.fromkeys(uniqueWords, 0)

for word in bagOfWordsA:
    numOfWordsA[word] += 1
numOfWordsA

{'الجامعة': 1,
 'ذهب': 1,
 'و': 1,
 'الكيمياء': 1,
 'الفيزياء': 1,
 'ذاكرت': 0,
 'مني': 0,
 'الرياضيات': 0,
 'الي': 1,
 'محمد': 1,
 'في': 0,
 'ليدرس': 1}

In [ ]:
numOfWordsB = dict.fromkeys(uniqueWords, 0)

for word in bagOfWordsB:
    numOfWordsB[word] += 1

numOfWordsB

{'الجامعة': 1,
 'ذهب': 0,
 'و': 1,
 'الكيمياء': 0,
 'الفيزياء': 1,
 'ذاكرت': 1,
 'مني': 1,
 'الرياضيات': 1,
 'الي': 0,
 'محمد': 0,
 'في': 1,
 'ليدرس': 0}

In [ ]:
def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

In [ ]:
tfA = computeTF(numOfWordsA, bagOfWordsA)
tfA

{'الجامعة': 0.125,
 'ذهب': 0.125,
 'و': 0.125,
 'الكيمياء': 0.125,
 'الفيزياء': 0.125,
 'ذاكرت': 0.0,
 'مني': 0.0,
 'الرياضيات': 0.0,
 'الي': 0.125,
 'محمد': 0.125,
 'في': 0.0,
 'ليدرس': 0.125}

In [ ]:
tfB = computeTF(numOfWordsB, bagOfWordsB)
tfB

{'الجامعة': 0.14285714285714285,
 'ذهب': 0.0,
 'و': 0.14285714285714285,
 'الكيمياء': 0.0,
 'الفيزياء': 0.14285714285714285,
 'ذاكرت': 0.14285714285714285,
 'مني': 0.14285714285714285,
 'الرياضيات': 0.14285714285714285,
 'الي': 0.0,
 'محمد': 0.0,
 'في': 0.14285714285714285,
 'ليدرس': 0.0}

In [ ]:
def computeIDF(documents):
    import math
    N = len(documents)

    idfDict = dict.fromkeys(documents[0].keys(), 0)
    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1

    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [ ]:
idfs = computeIDF([numOfWordsA, numOfWordsB])
idfs

{'الجامعة': 0.0,
 'ذهب': 0.6931471805599453,
 'و': 0.0,
 'الكيمياء': 0.6931471805599453,
 'الفيزياء': 0.0,
 'ذاكرت': 0.6931471805599453,
 'مني': 0.6931471805599453,
 'الرياضيات': 0.6931471805599453,
 'الي': 0.6931471805599453,
 'محمد': 0.6931471805599453,
 'في': 0.6931471805599453,
 'ليدرس': 0.6931471805599453}

In [ ]:
def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [ ]:
tfidfA = computeTFIDF(tfA, idfs)
tfidfA

{'الجامعة': 0.0,
 'ذهب': 0.08664339756999316,
 'و': 0.0,
 'الكيمياء': 0.08664339756999316,
 'الفيزياء': 0.0,
 'ذاكرت': 0.0,
 'مني': 0.0,
 'الرياضيات': 0.0,
 'الي': 0.08664339756999316,
 'محمد': 0.08664339756999316,
 'في': 0.0,
 'ليدرس': 0.08664339756999316}

In [ ]:
tfidfB = computeTFIDF(tfB, idfs)
tfidfB

{'الجامعة': 0.0,
 'ذهب': 0.0,
 'و': 0.0,
 'الكيمياء': 0.0,
 'الفيزياء': 0.0,
 'ذاكرت': 0.09902102579427789,
 'مني': 0.09902102579427789,
 'الرياضيات': 0.09902102579427789,
 'الي': 0.0,
 'محمد': 0.0,
 'في': 0.09902102579427789,
 'ليدرس': 0.0}

In [ ]:
df = pd.DataFrame([tfidfA, tfidfB])
df.head()

,الجامعة,ذهب,و,الكيمياء,الفيزياء,ذاكرت,مني,الرياضيات,الي,محمد,في,ليدرس
0,0.0,0.086643,0.0,0.086643,0.0,0.000000,0.000000,0.000000,0.086643,0.086643,0.000000,0.086643
1,0.0,0.000000,0.0,0.000000,0.0,0.099021,0.099021,0.099021,0.000000,0.000000,0.099021,0.000000

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([documentA, documentB])
print(vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13 stored elements and shape (2, 11)>
  Coords	Values
  (0, 6)	0.4078241041497786
  (0, 9)	0.4078241041497786
  (0, 4)	0.4078241041497786
  (0, 0)	0.29017020899133733
  (0, 8)	0.4078241041497786
  (0, 2)	0.29017020899133733
  (0, 3)	0.4078241041497786
  (1, 0)	0.31779953783628945
  (1, 2)	0.31779953783628945
  (1, 5)	0.4466561618018052
  (1, 10)	0.4466561618018052
  (1, 1)	0.4466561618018052
  (1, 7)	0.4466561618018052

In [ ]:
feature_names = vectorizer.get_feature_names_out()
feature_names

array(['الجامعة', 'الرياضيات', 'الفيزياء', 'الكيمياء', 'الي', 'ذاكرت',
       'ذهب', 'في', 'ليدرس', 'محمد', 'مني'], dtype=object)

In [ ]:
dense = vectors.todense()
dense

matrix([[0.29017021, 0.        , 0.29017021, 0.4078241 , 0.4078241 ,
         0.        , 0.4078241 , 0.        , 0.4078241 , 0.4078241 ,
         0.        ],
        [0.31779954, 0.44665616, 0.31779954, 0.        , 0.        ,
         0.44665616, 0.        , 0.44665616, 0.        , 0.        ,
         0.44665616]])

In [ ]:
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)
df.head()

,الجامعة,الرياضيات,الفيزياء,الكيمياء,الي,ذاكرت,ذهب,في,ليدرس,محمد,مني
0,0.29017,0.000000,0.29017,0.407824,0.407824,0.000000,0.407824,0.000000,0.407824,0.407824,0.000000
1,0.31780,0.446656,0.31780,0.000000,0.000000,0.446656,0.000000,0.446656,0.000000,0.000000,0.446656