In [1]:
import re,string,requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
def retrieve_docs_and_clean():
    r = requests.get('https://bola.kompas.com/')

    soup = BeautifulSoup(r.content, 'html.parser')

    link = []
    for i in soup.find('div', {'class':'most__wrap'}).find_all('a'):
        i['href'] = i['href'] + '?page=all'
        link.append(i['href'])

    print(f'Number of links is ({len(link)})')
    print(f'second link is \n')
    print(link[1])
    print('===============================')
    documents = []
    for i in link:
        r = requests.get(i)
        soup = BeautifulSoup(r.content, 'html.parser')

        sen = []
        content_div = soup.find('div', {'class':'read__content'})
        if content_div:
            for p_tag in content_div.find_all('p'):
                sen.append(p_tag.text)
            if sen:
                print(f'number of sentences is {len(sen)} and first sentence is ({sen[0]})')
                documents.append(' '.join(sen))
            else:
                print(f'No sentences found in content_div for link: {i}')
        else:
            print(f"'read__content' div not found for link: {i}")
    print('===============================')
    documents_clean = []
    for d in documents:
        # Correcting the regex pattern to use unicode escape sequence to avoid SyntaxError
        document_test = re.sub(r'[^\u0000-\u007F]+', ' ', d)
        document_test = re.sub(r'@\w+', '', document_test)
        document_test = document_test.lower()
        document_test = re.sub(r'[%s]' % re.escape(string.punctuation), ' ', document_test)
        document_test = re.sub(r'[0-9]', '', document_test)
        document_test = re.sub(r'\s{2,}', ' ', document_test)
        documents_clean.append(document_test)

    print(documents_clean)
    return documents_clean


def get_similar_articles(q, df):
    print("query:", q)
    print("Article with the highest cosine similarity value: ")
    q = [q]
    q_vec = vectorizer.transform(q).toarray().reshape(df.shape[0],)
    print(f'QVec shape is ({q_vec.shape})')
    sim = {}
    # Iterate up to the number of documents (columns in df) to avoid KeyError
    for i in range(df.shape[1]):
        # Ensure the column exists before attempting calculation
        if i in df.columns:
            sim[i] = np.dot(df.loc[:, i].values, q_vec) / np.linalg.norm(df.loc[:, i]) * np.linalg.norm(q_vec)
        else:
            print(f"Warning: Column {i} not found in DataFrame. Skipping.")

    print(sim)
    sim_sorted = sorted(sim.items(), key=lambda x: x[1], reverse=True)

    for k, v in sim_sorted:
        if v != 0.0:
            print("Similarity Value:", v)
            print(docs[k])
            print()

In [14]:
docs = retrieve_docs_and_clean()

Number of links is (10)
second link is

https://bola.kompas.com/read/2026/07/27/05185038/persija-takluk-0-1-dari-persebaya-shin-tae-yong-soroti-minimnya-waktu-persiapan?page=all
===============================
number of sentences is 29 and first sentence is (KOMPAS.com - Duel Timnas Indonesia vs Kamboja dalam Piala AFF atau ASEAN Championship 2026 akan berlangsung pada Senin (27/7/2026) pukul 20.30 WIB. Simak prediksi skor dalam artikel ini.)
number of sentences is 30 and first sentence is (KOMPAS.com - Pelatih Persija Jakarta, Shin Tae-yong, tetap mengapresiasi daya juang dan determinasi anak asuhnya di lapangan hijau meskipun harus menelan kekalahan tipis 0-1 dari Persebaya Surabaya.)
number of sentences is 31 and first sentence is (KOMPAS.com - Laga Timnas Indonesia vs Kamboja dalam Piala AFF atau ASEAN Championship 2026 akan berlangsung pada Senin (27/7/2026) pukul 20.30 WIB. Simak prediksi line-up dalam artikel ini.)
number of sentences is 26 and first sentence is (KOMPAS.com - Pertandingan Timnas Indonesia vs Kamboja dalam Piala AFF atau ASEAN Championship 2026 akan berlangsung pada Senin (27/7/2026) pukul 20.30 WIB. Simak siaran langsung dalam artikel ini.)
'read__content' div not found for link: https://www.kompas.com/sports/read/2026/07/27/05040188/daftar-pemain-terbaik-sea-v-cup-2026-leg-2-ada-nama-hendra-kurniawan?page=all
'read__content' div not found for link: https://bola.kompas.com/read/2026/07/27/11025578/penunjukan-andrea-pirlo-sebagai-pelatih-timnas-italia-dihadang-ganjalan-politik?page=all
number of sentences is 29 and first sentence is (KOMPAS.com - Penjaga gawang utama Timnas Belgia, Thibaut Courtois, memberikan respons yang sangat positif atas terpilihnya Mark van Bommel sebagai pelatih kepala yang baru.)
number of sentences is 38 and first sentence is (KOMPAS.com - John Herdman memimpin era baru Timnas Indonesia di ASEAN Championship 2026 (Piala AFF 2026) saat menjamu Kamboja dalam laga perdana Grup A.)
'read__content' div not found for link: https://bola.kompas.com/read/2026/07/27/10493128/regenerasi-atau-prestasi-pengamat-soroti-pilihan-herdman-dalam-menyusun-skuad?page=all
'read__content' div not found for link: https://bola.kompas.com/read/2026/07/27/14000078/dpmm-fc-vs-persib-menang-clean-sheet-modal-berharga-maung?page=all
===============================

In [15]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(docs)
X.shape

(6, 994)

In [16]:
df = pd.DataFrame(X.T.toarray(), index=vectorizer.get_feature_names_out())
print(df.shape)
df.head(20)

(994, 6)

                 0         1         2         3         4         5
abdel     0.000000  0.000000  0.040025  0.000000  0.000000  0.000000
absen     0.041291  0.000000  0.000000  0.000000  0.000000  0.000000
ada       0.024496  0.018813  0.000000  0.000000  0.019832  0.017079
adalah    0.042309  0.000000  0.102529  0.093445  0.034254  0.029498
adanya    0.000000  0.000000  0.000000  0.000000  0.033429  0.000000
aff       0.073489  0.000000  0.071235  0.081155  0.000000  0.119551
agar      0.041291  0.000000  0.000000  0.000000  0.000000  0.000000
agung     0.000000  0.000000  0.040025  0.000000  0.000000  0.000000
air       0.000000  0.000000  0.000000  0.045598  0.000000  0.000000
akan      0.091645  0.042231  0.142136  0.141687  0.089036  0.038337
akar      0.000000  0.031712  0.000000  0.000000  0.000000  0.000000
akhir     0.000000  0.000000  0.083129  0.126273  0.023144  0.000000
akhirnya  0.000000  0.000000  0.000000  0.000000  0.033429  0.000000
akibat    0.000000  0.026004  0.000000  0.000000  0.027413  0.000000
alami     0.000000  0.000000  0.000000  0.000000  0.033429  0.000000
alisher   0.000000  0.000000  0.040025  0.000000  0.000000  0.000000
amat      0.028586  0.000000  0.027710  0.000000  0.000000  0.019930
amerika   0.000000  0.000000  0.000000  0.000000  0.066859  0.000000
anak      0.024496  0.037627  0.047490  0.027052  0.000000  0.000000
ancaman   0.000000  0.031712  0.000000  0.000000  0.000000  0.000000

In [17]:
df.tail(20)

                 0         1         2         3         4         5
wajah     0.000000  0.000000  0.000000  0.000000  0.000000  0.028788
waktu     0.033859  0.078013  0.000000  0.000000  0.000000  0.000000
walaupun  0.028586  0.000000  0.027710  0.031568  0.000000  0.000000
walsh     0.000000  0.000000  0.040025  0.000000  0.000000  0.000000
warna     0.000000  0.000000  0.000000  0.000000  0.000000  0.028788
warriors  0.041291  0.000000  0.000000  0.000000  0.000000  0.000000
wasit     0.000000  0.031712  0.000000  0.000000  0.000000  0.000000
waspadai  0.041291  0.000000  0.000000  0.000000  0.000000  0.000000
wejangan  0.033859  0.000000  0.032821  0.000000  0.000000  0.000000
wib       0.018329  0.014077  0.017767  0.020241  0.014839  0.012779
wni       0.000000  0.000000  0.000000  0.000000  0.000000  0.057576
xi        0.000000  0.031712  0.000000  0.000000  0.000000  0.000000
xinhua    0.000000  0.000000  0.000000  0.000000  0.033429  0.000000
ya        0.028586  0.000000  0.027710  0.031568  0.000000  0.000000
yakin     0.000000  0.000000  0.032821  0.000000  0.027413  0.000000
yang      0.238277  0.253384  0.142136  0.161928  0.178072  0.115011
yong      0.000000  0.221984  0.000000  0.000000  0.000000  0.000000
yudai     0.000000  0.000000  0.040025  0.000000  0.000000  0.000000
yudha     0.041291  0.000000  0.000000  0.000000  0.000000  0.000000
yuran     0.000000  0.031712  0.000000  0.000000  0.000000  0.000000

In [18]:
q = 'windy'
get_similar_articles(q, df)

query: windy
Article with the highest cosine similarity value:
QVec shape is ((994,))
{0: np.float64(0.0), 1: np.float64(0.0), 2: np.float64(0.0), 3: np.float64(0.0), 4: np.float64(0.0), 5: np.float64(0.0)}

In [19]:
q = 'adalah'
get_similar_articles(q, df)

query: adalah
Article with the highest cosine similarity value:
QVec shape is ((994,))
{0: np.float64(0.04230880272453317), 1: np.float64(0.0), 2: np.float64(0.10252912948164647), 3: np.float64(0.0934446372134152), 4: np.float64(0.03425359808603547), 5: np.float64(0.029497706834724177)}
Similarity Value: 0.10252912948164647
kompas com laga timnas indonesia vs kamboja dalam piala aff atau asean championship akan berlangsung pada senin pukul wib simak prediksi line up dalam artikel ini duel grup a asean championship timnas indonesia vs kamboja bakal digelar di stadion pakansari bogor pertandingan tersebut merupakan kans emas bagi skuad garuda untuk meraup tiga poin penuh saat ini posisi timnas indonesia masih tertahan di urutan ketiga klasemen grup a terpaut tiga angka dari vietnam dan singapura yang sudah bertanding lebih dulu menjelang partai timnas indonesia vs kamboja ini catatan sejarah secara telak berpihak kepada kubu tuan rumah baca juga prediksi skor timnas indonesia vs kamboja di grup a asean championship dari lima perjumpaan terakhir seluruhnya berhasil disapu bersih dengan kemenangan oleh tim merah putih atas kamboja walaupun di atas kertas berstatus unggulan john herdman selaku pelatih kepala menolak untuk meremehkan musuhnya juru taktik berpaspor inggris tersebut secara khusus menyoroti kedisiplinan serta struktur taktik tim lawan yang dinilai berpotensi merepotkan barisan pertahanannya kami telah mengamati permainan kamboja mereka adalah tim yang terstruktur dan sangat disiplin mereka akan menjadi lawan yang berat ujar herdman dikutip dari antara senin menghadapi partai perdana ini sang pelatih telah memberikan wejangan mendalam kepada anak asuhnya selama masa pemusatan latihan pertandingan ini dinilai amat krusial guna mematangkan koneksi antarpemain serta mempraktikkan strategi yang sudah dirancang dengan saksama baca juga timnas indonesia masih tunggu kepastian justin hubner bergabung di piala aff fokus kami adalah pada identitas taktik koneksi chemistry dan semangat kami jika kami bisa menunjukkan permainan terbaik saya percaya kami akan baik baik saja lanjut john herdman dokumentasi bali united pelatih timnas indonesia saat memimpin pemusatan latihan di bali sejak juli john herdman herdman tidak menutup mata bahwa kubu lawan mendapat sedikit keuntungan teknis lantaran sudah mencicipi atmosfer kompetisi di laga sebelumnya sehingga ritme permainan mereka cenderung lebih hidup kamboja telah menjalani satu pertandingan jadi mereka memiliki ritme yang baik mereka akan siap namun kami harus tetap fokus pada apa yang telah kami bangun bersama pungkasnya ketika dikonfirmasi herdman mengatakan marselino ferdinan memang mengalami benturan dalam salah satu sesi latihan makanya kebugarannya masih perlu dipantau dalam beberapa hari ke depan ya kami sedang memantau marselino saat ini dia terkena sedikit benturan dalam salah satu latihan kami ungkap herdman dalam konferensi pers di stadion pakansari bogor minggu jadi ini adalah tindakan pencegahan kami akan menanganinya selama beberapa hari ke depan imbuhnya lebih lanjut herdman juga menyatakan bahwa sang pemain akan menjalani tes kebugaran hari ini untuk memastikan kondisinya baca juga siapa kapten timnas indonesia di piala aff sumardji beri bocoran namun ia yakin penggawanya itu akan bisa bermain dan memberi dampak di dalam permainan saat nantinya diturunkan dalam pertandingan dia akan menjalani tes kebugaran hari ini atau besok untuk melihat ketersediaannya ujar john herdman melanjutkan tapi marselino adalah anak yang tangguh dia telah melewati beberapa momen sulit akhir akhir ini dan secara mental dia sangat kuat dia sudah sangat tidak sabar untuk bermain itu sudah pasti tutup pelatih kelahiran kelahiran consett pada juli itu berikut adalah prakiraan susunan pemain dan skor akhir untuk laga timnas indonesia vs kamboja sportskeeda timnas indonesia vs kamboja timnas indonesia nadeo argawinata gk rizky ridho c kadek agung mithcell baker sandy walsh ivar jenner thom haye dony tri pamungkas beckham putra ragnar oratmangoen mitchell baker kamboja kimhuy hul gk c ouh sovann hikaru mizuno dimong sophal phat sokha mat noron alisher mirzaev yudai ogawa iago abdel coulibaly bong samuel

Similarity Value: 0.0934446372134152
kompas com pertandingan timnas indonesia vs kamboja dalam piala aff atau asean championship akan berlangsung pada senin pukul wib simak siaran langsung dalam artikel ini laga grup a asean championship timnas indonesia vs kamboja bakal digelar di stadion pakansari bogor duel tersebut merupakan kans emas bagi timnas indonesia untuk mengamankan tiga poin penuh saat ini rangkaian persiapan akhir jelang laga timnas indonesia vs kamboja terus dimatangkan oleh jajaran pelatih demi memperbaiki posisi di klasemen sementara grup a baca juga prediksi skor timnas indonesia vs kamboja di grup a asean championship walaupun di atas kertas berstatus unggulan pelatih kepala john herdman dengan tegas menolak untuk memandang sebelah mata kekuatan sang lawan pelatih menyoroti struktur permainan tim tamu yang sangat teratur kami telah mengamati permainan kamboja mereka adalah tim yang terstruktur dan sangat disiplin mereka akan menjadi lawan yang berat kata herdman dikutip dari antara senin ia juga menekankan pentingnya menjaga identitas permainan dan koneksi antarpemain di atas lapangan hijau selain itu ia menyadari bahwa lawan memiliki keunggulan dari segi ritme bertanding yang sudah teruji di laga sebelumnya fokus kami adalah pada identitas taktik koneksi chemistry dan semangat kami jika kami bisa menunjukkan permainan terbaik saya percaya kami akan baik baik saja imbuhnya kamboja telah menjalani satu pertandingan jadi mereka memiliki ritme yang baik mereka akan siap namun kami harus tetap fokus pada apa yang telah kami bangun bersama baca juga timnas indonesia masih tunggu kepastian justin hubner bergabung di piala aff dokumentasi bali united pemain timnas indonesia saat latihan bersama untuk mempersiapakan mengarungi asean championship di bali united training center pantai purnama gianyar bali di sisi lain persiapan tim sempat diwarnai oleh kondisi marselino ferdinan yang mengalami sedikit masalah kebugaran setelah mendapat benturan dalam sesi latihan ya kami sedang memantau marselino saat ini dia terkena sedikit benturan dalam salah satu latihan kami tegas john herdman dalam konferensi pers di stadion pakansari bogor minggu jadi ini adalah tindakan pencegahan kami akan menanganinya selama beberapa hari ke depan ujar menambahkan tim pelatih akan terus memantau perkembangan sang pemain melalui serangkaian tes sebelum mengambil keputusan akhir dia akan menjalani tes kebugaran hari ini atau besok untuk melihat ketersediaannya ujar john herdman melanjutkan tapi marselino adalah anak yang tangguh dia telah melewati beberapa momen sulit akhir akhir ini dan secara mental dia sangat kuat dia sudah sangat tidak sabar untuk bermain itu sudah pasti pungkas pria berusia tahun itu baca juga siapa kapten timnas indonesia di piala aff sumardji beri bocoran duel timnas indonesia menghadapi kamboja dapat disaksikan lewat siaran langsung televisi swasta nasional rcti selain itu pecinta sepak bola tanah air dapat menonton laga tersebut melalui link live streaming berikut link live streaming jangan lewatkan pertandingan seru timnas indonesia vs kamboja pada grup a asean championship

Similarity Value: 0.04230880272453317
kompas com duel timnas indonesia vs kamboja dalam piala aff atau asean championship akan berlangsung pada senin pukul wib simak prediksi skor dalam artikel ini pertandingan grup a asean championship timnas indonesia vs kamboja bakal digelar di stadion pakansari bogor laga tersebut menjadi kesempatan bagi skuad garuda julukan timnas indonesia untuk meraih tiga poin saat ini posisi timnas indonesia masih tertahan di urutan ketiga klasemen grup a terpaut tiga angka dari vietnam dan singapura yang sudah bertanding lebih dulu menjelang partai timnas indonesia vs kamboja ini catatan sejarah secara telak berpihak kepada tuan rumah baca juga timnas indonesia masih tunggu kepastian justin hubner bergabung di piala aff sebab dari lima perjumpaan terakhir seluruhnya berhasil disapu bersih dengan kemenangan oleh tim merah putih atas kamboja walaupun di atas kertas berstatus unggulan john herdman selaku pelatih kepala menolak untuk meremehkan musuhnya juru taktik berpaspor inggris tersebut secara khusus menyoroti kedisiplinan serta struktur taktik tim lawan yang dinilai berpotensi merepotkan barisan pertahanannya kami telah mengamati permainan kamboja mereka adalah tim yang terstruktur dan sangat disiplin mereka akan menjadi lawan yang berat ungkap herdman dikutip dari antara senin menghadapi partai perdana ini sang pelatih telah memberikan wejangan mendalam kepada anak asuhnya selama masa pemusatan latihan pertandingan ini dinilai amat krusial guna mematangkan koneksi antarpemain serta mempraktikkan strategi yang sudah dirancang dengan saksama baca juga siapa kapten timnas indonesia di piala aff sumardji beri bocoran fokus kami adalah pada identitas taktik koneksi chemistry dan semangat kami ujar herdman kompas com pratama yudha pelatih timnas indonesia john herdman dan nadeo argawinata ia juga meyakini bahwa pasukannya mampu menampilkan performa puncak untuk merengkuh hasil maksimal jika kami bisa menunjukkan permainan terbaik saya percaya kami akan baik baik saja jelasnya herdman tidak menutup mata bahwa kubu lawan mendapat sedikit keuntungan teknis lantaran sudah mencicipi atmosfer kompetisi di laga sebelumnya sehingga ritme permainan mereka cenderung lebih hidup kamboja telah menjalani satu pertandingan jadi mereka memiliki ritme yang baik mereka akan siap namun kami harus tetap fokus pada apa yang telah kami bangun bersama tambahnya selaras dengan sang pelatih penjaga gawang nadeo argawinata menyatakan ketegasannya bahwa tim nasional pantang memandang sebelah mata armada angkor warriors tersebut kami telah melihat pertandingan kamboja melawan singapura tetapi itu tidak membuat kami menganggap mereka tim yang mudah untuk dikalahkan kami tetap fokus pada identitas permainan kami sendiri dan mengikuti instruksi pelatih kata nadeo baca juga timnas indonesia waspadai kamboja enggan remehkan lawan yang baru kalah kabar kurang menggembirakan justru datang dari ketua badan tim nasional btn sumardji pihaknya memberikan sinyal kuat bahwa pilar muda marselino ferdinan kemungkinan absen dari lapangan pada laga awal ini pemain berbakat tersebut menderita cedera ketika melakoni sesi latihan di bali yang memaksanya menepi ke tribune dengan langkah terpincang saat tim menjalani latihan resmi pranit untuk lino perlu saya sampaikan memang di latihan terakhir dia sedikit ada persoalan dan tim dokter kami sedang mengobservasi berdasarkan mri yang tadi pagi dilakukan ujar sumardji di sela sela latihan resmi timnas indonesia di stadion madya gelora bung karno gbk jakarta minggu ya mudah mudahan dalam waktu yang dekat bisa kembali berlatih dengan tim yang pasti tim dokter akan memantau perkembangan lino agar supaya lino bisa mendapatkan perhatian jelasnya sportskeeda timnas indonesia vs kamboja

Similarity Value: 0.03425359808603547
kompas com penjaga gawang utama timnas belgia thibaut courtois memberikan respons yang sangat positif atas terpilihnya mark van bommel sebagai pelatih kepala yang baru rencananya ia bakal segera menjadwalkan pembicaraan tatap muka dengan sang pelatih untuk membahas masa depannya bersama tim nasional belgia kedatangan van bommel sendiri terjadi beberapa pekan pascagugurnya timnas belgia di babak perempat final piala dunia hasil minor tersebut membuat rudi garcia kehilangan posisinya di mana pelatih asal prancis itu bersama pihak federasi telah sepakat untuk tidak lagi memperpanjang masa bakti terkait van bommel yang diplot secara kilat untuk memimpin timnas belgia courtois sangat yakin bahwa sosok mantan pemain timnas belanda itu akan mendapatkan respek tinggi dari ruang ganti baca juga belgia cuma sampai besar piala dunia kontrak rudi garcia tak diperpanjang itu sebenarnya bukan kejutan karena namanya sudah beredar cukup lama kata courtois dikutip dari reuters senin saya rasa dia telah membuktikan di antwerp bahwa dia adalah pelatih top banyak pemain yang berbicara sangat positif tentang dia jadi saya berharap dapat mengenalnya lebih baik kiprah impresifnya kala menukangi royal antwerp memang dinilai sebagai modal kuat sang pelatih yang terpenting adalah van bommel sendiri pernah bermain di level tertinggi dan tahu bagaimana rasanya bermain dalam pertandingan seperti ini pengalaman di level tertinggi itu jelas merupakan hal positif dan secara alami mendapatkan banyak rasa hormat dari para pemain katanya meski menyambut baik sang pelatih kepastian mengenai apakah kiper berusia tahun ini akan terus merumput di bawah asuhan van bommel masih diselimuti tanda tanya baca juga de bruyne dan courtois ungkap masa depan di timnas belgia usai piala dunia selepas turnamen piala dunia ia sempat menegaskan kesediaannya untuk terus membela timnas asalkan dirinya diizinkan untuk melewati gelaran nations league yang akan datang xinhua cao can pemain timnas belgia dodi lukebakio kanan pertama melompat untuk melakukan sundulan selama pertandingan babak besar antara timnas amerika serikat dan belgia di piala dunia fifa di seattle stadium seattle amerika serikat pada selasa pagi wib setelah piala dunia saya tentu masih ingin melanjutkan tetapi itu akan bergantung pada percakapan yang saya lakukan dengannya kata courtois saya ingin beristirahat selama nations league dan kita harus mencoba mencapai kesepakatan mengenai hal itu setelah itu saya akan memutuskan apakah saya ingin melanjutkan atau tidak dalam kesempatan tersebut courtois turut mengenang momen pahit saat timnya harus angkat koper dari piala dunia insiden itu bermula saat ia dibekap cedera dalam laga krusial perempat final menghadapi spanyol di los angeles pada juli lalu sang kiper pengganti senne lammens kemudian melakukan kesalahan krusial yang mengantarkan spanyol meraih kemenangan dan pada akhirnya keluar sebagai kampiun kala itu ia meyakini dirinya masih mampu untuk terus bertanding dan ia kembali mempertegas pandangannya tersebut pada akhir pekan kemarin baca juga mainkan lammens lawan spanyol pelatih belgia disemprot ibrahimovic saya hanya merasa bahwa saya tidak bisa lagi mengambil tendangan gawang seorang pemain bertahan bisa saja mengambil bola itu saat permainan terbuka saya masih bisa melakukan umpan menyamping tapi pelatih berkata kita sudah sepakat bahwa hanya pemain yang fit yang akan bermain baik tidak masalah lebih jauh penjaga gawang andalan ini menepis anggapan adanya konflik personal dengan rudi garcia pelatih yang sempat dihujani kritik tajam akibat sejumlah keputusannya tentu saja saya kecewa karena itu melawan spanyol dan kami sedang dalam ritme yang bagus tetapi tim lebih penting daripada saya keputusan itu sudah dibuat dan tidak pernah ada permusuhan saya tidak pernah ingin berbicara buruk tentang dia garcia tambahnya

Similarity Value: 0.029497706834724177
kompas com john herdman memimpin era baru timnas indonesia di asean championship piala aff saat menjamu kamboja dalam laga perdana grup a pertandingan timnas indonesia vs kamboja akan berlangsung di stadion pakansari cibinong bogor senin pukul wib john herdman telah menentukan nama yang akan dibawanya ke piala aff dengan sebagian besar merupakan wajah lama namun ada lima pemain muda di skuad garuda yang berpotensi debut bagi timnas indonesia di piala aff baca juga pesan jay idzes ke timnas indonesia jelang asean championship pemain pemain tersebut adalah mitchell baker tim geypens jens raven brian fatari dan rizky eka pratama bahkan john herdman memberi slot penyerang murni timnas indonesia di piala aff khsusu kepada mitchell baker dan jens raven tercatat hanya jens raven yang pernah memakai seragam timnas indonesia meski di kelompok usia saat tampil di turnamen resmi tim geypens sempat menjadi bagian dari timnas u indonesia saat bermain di turnamen maurice revello di perancis namun statusnya kala itu belum menjadi wni siapa saja nama nama calon debutan timnas indonesia di piala aff baca juga head to head timnas indonesia vs kamboja garuda masih terlalu perkasa mitchell baker mitchell baker merupakan pemain naturalisasi terbaru di timnas indonesia setelah resmi menjadi wni pada juli bersama luke vickery pemain yang kini bermain untuk vermont green fc tersebut menjadi salah dua pemain yang masuk ke dalam proyek naturalisasi baru berbeda dari luke vickery yang tak dilepas klubnya macarthur fc baker berpotensi melakoni debut internasionalnya bersama skuad garuda baker akan menjadi ujung tombak timnas indonesia dan diharapkan bisa memberi warna bagi para penyerang garuda baca juga regenerasi atau prestasi pengamat soroti pilihan herdman dalam menyusun skuad timnas indonesia tim geypens tim geypens mendapat kesempatan untuk melakukan debut di tim senior setelah namanya dipilih oleh herdman untuk piala aff bek kiri berusia tahun ini sebelumnya telah bermain untuk timnas indonesia u di bawah arahan indra sjafri dengan total empat penampilan pengalaman tersebut didapatnya saat mengikuti touloun cup di mana ia menghadapi tim tim seperti ukraina u dan jepang u musim lalu geypens mencatatkan penampilan untuk fc emmen di liga belanda dengan dua gol dan dua assist baca juga jadwal siaran langsung timnas indonesia vs kamboja di asean championship dokumentasi bali united pemain timnas indonesia eliano reijnders thom haye jordi amat dan jens raven bersiap untuk latihan bersama untuk mempersiapakan mengarungi asean championship di bali united training center pantai purnama gianyar bali jens raven jens raven berpotensi debut bersama timnas indonesia meski namanya sempat dipanggil untuk bergabung ke tim jelang fifa matchday juni lalu raven yang merupakan rekan setim tim gaypens telah mencetak gol dari penampilan di semua kelompok usia timnas indonesia pemain didikan dordrecht tersebut tentu tak ingin melewatkan kesempatan ini untuk membuktikan kualitasnya baca juga prediksi skor timnas indonesia vs kamboja di grup a asean championship brian fatari brian fatari menjadi salah satu pemain yang memiliki peluang untuk debut di timnas indonesia bek tengah berusia tahun ini tampil menjanjikan bersama dewa united banten fc dengan penampilan dan dua assist musim lalu pada musim sebelumnya dia juga menunjukkan performa baik dengan penampilan termasuk penampilan terakhir secara berturut turut di liga baca juga timnas indonesia masih tunggu kepastian justin hubner bergabung di piala aff rizky eka pratama pemain terakhir yang berpeluang debut adalah rizky eka pratama penyerang sayap kiri dari psm makassar rizky telah menghabiskan seluruh kariernya di psm dan mencatatkan penampilan dengan enam gol dan assist dalam dua musim terakhir menit bermainnya meningkat pesat dengan penampilan dan total menit bermain

In [20]:
q = 'wang'
get_similar_articles(q, df)

query: wang
Article with the highest cosine similarity value:
QVec shape is ((994,))
{0: np.float64(0.0), 1: np.float64(0.0), 2: np.float64(0.0), 3: np.float64(0.0), 4: np.float64(0.0), 5: np.float64(0.0)}