In [ ]:
import pandas as pd

filepath_dict = {'yelp':   'yelp_labelled.txt',
                 'amazon': 'amazon_cells_labelled.txt',
                 'imdb':   'imdb_labelled.txt'}

df_list = []
for source, filepath in filepath_dict.items():
    df = pd.read_csv(filepath, names=['sentence', 'label'], sep='\t')
    df['source'] = source  # Add another column filled with the source name
    print(df.head())
    print(df.info())

    df_list.append(df)

df = pd.concat(df_list)
print(df.iloc[0])

                                            sentence  label source
0                           Wow... Loved this place.      1   yelp
1                                 Crust is not good.      0   yelp
2          Not tasty and the texture was just nasty.      0   yelp
3  Stopped by during the late May bank holiday of...      1   yelp
4  The selection on the menu was great and so wer...      1   yelp
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sentence  1000 non-null   object
 1   label     1000 non-null   int64
 2   source    1000 non-null   object
dtypes: int64(1), object(2)
memory usage: 23.6+ KB
None
                                            sentence  label  source
0  So there is no way for me to plug it in here i...      0  amazon
1                        Good case, Excellent value.      1  amazon
2                             Great for the jawbone.      1  amazon
3  Tied to charger for conversations lasting more...      0  amazon
4                                  The mic is great.      1  amazon
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sentence  1000 non-null   object
 1   label     1000 non-null   int64
 2   source    1000 non-null   object
dtypes: int64(1), object(2)
memory usage: 23.6+ KB
None
                                            sentence  label source
0  A very, very, very slow-moving, aimless movie ...      0   imdb
1  Not sure who was more lost - the flat characte...      0   imdb
2  Attempting artiness with black & white and cle...      0   imdb
3       Very little music or anything to speak of.        0   imdb
4  The best scene in the movie was when Gerardo i...      1   imdb
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sentence  748 non-null    object
 1   label     748 non-null    int64
 2   source    748 non-null    object
dtypes: int64(1), object(2)
memory usage: 17.7+ KB
None
sentence    Wow... Loved this place.
label                              1
source                          yelp
Name: 0, dtype: object

In [ ]:
df.shape

(2748, 3)

In [ ]:
print(df.head())
print(df.info())
print(df.describe())

                                            sentence  label source
0                           Wow... Loved this place.      1   yelp
1                                 Crust is not good.      0   yelp
2          Not tasty and the texture was just nasty.      0   yelp
3  Stopped by during the late May bank holiday of...      1   yelp
4  The selection on the menu was great and so wer...      1   yelp
<class 'pandas.core.frame.DataFrame'>
Index: 2748 entries, 0 to 747
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sentence  2748 non-null   object
 1   label     2748 non-null   int64
 2   source    2748 non-null   object
dtypes: int64(1), object(2)
memory usage: 85.9+ KB
None
             label
count  2748.000000
mean      0.504367
std       0.500072
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

In [ ]:
df['label'].value_counts()

label
1    1386
0    1362
Name: count, dtype: int64

In [ ]:
df['source'].value_counts()

source
yelp      1000
amazon    1000
imdb       748
Name: count, dtype: int64

In [ ]:
sentences = ['John likes ice cream', 'John hates chocolate.']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(lowercase=False)
sentences_cv=vectorizer.fit_transform(sentences)
vectorizer.vocabulary_

{'John': 0, 'likes': 5, 'ice': 4, 'cream': 2, 'hates': 3, 'chocolate': 1}

In [ ]:
sentences_cv.toarray()

array([[1, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0]])

In [ ]:
from sklearn.model_selection import train_test_split

df_yelp = df[df['source'] == 'yelp']

sentences = df_yelp['sentence'].values
# print(sentences)
y = df_yelp['label'].values
# print(y)
sentences_train, sentences_test, y_train, y_test = train_test_split(
   sentences, y, test_size=0.25, random_state=1000)

In [ ]:
list(sentences_train)[:10]

['The food was barely lukewarm, so it must have been sitting waiting for the server to bring it out to us.',
 'Sorry, I will not be getting food from here anytime soon :(',
 'Of all the dishes, the salmon was the best, but all were great.',
 'The fries were not hot, and neither was my burger.',
 "In fact I'm going to round up to 4 stars, just because she was so awesome.",
 'Will go back next trip out.',
 'This was my first crawfish experience, and it was delicious!',
 "I could barely stomach the meal, but didn't complain because it was a business lunch.",
 'A great way to finish a great.',
 'Best service and food ever, Maria our server was so good and friendly she made our day.']

In [ ]:
list(y_train)[:10]

[0, 0, 1, 0, 1, 1, 1, 0, 1, 1]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_train=vectorizer.fit_transform(sentences_train)

X_test  = vectorizer.transform(sentences_test)
X_train

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7368 stored elements and shape (750, 1714)>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)

print("Accuracy:", score)
pred=classifier.predict(X_test)
acc_score=accuracy_score(y_test,pred)
print("Accuracy Score:",acc_score)

Accuracy: 0.796
Accuracy Score: 0.796

In [ ]:
list(set(df["source"].values))

['imdb', 'amazon', 'yelp']

In [ ]:
df['source'].unique()

array(['yelp', 'amazon', 'imdb'], dtype=object)

In [ ]:
df['source'].nunique()

3

In [ ]:
for source in df['source'].unique(): # yelp , imdb , amazon
    df_source = df[df['source'] == source]
    # print(df_source)
    sentences = df_source['sentence'].values
    y = df_source['label'].values

    sentences_train, sentences_test, y_train, y_test = train_test_split(
        sentences, y, test_size=0.25, random_state=1000)

    vectorizer = CountVectorizer()
    vectorizer.fit(sentences_train)
    X_train = vectorizer.transform(sentences_train)
    X_test  = vectorizer.transform(sentences_test)

    classifier = LogisticRegression()
    classifier.fit(X_train, y_train)
    score = classifier.score(X_test, y_test)
    print('Accuracy for {} data: {:.4f}'.format(source, score))

Accuracy for yelp data: 0.7960
Accuracy for amazon data: 0.7960
Accuracy for imdb data: 0.7487

In [ ]:
x=df['sentence']
y=df['label']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1000)
vectorizer = CountVectorizer()
vectorizer.fit(x_train)
X_train = vectorizer.transform(x_train)
X_test  = vectorizer.transform(x_test)
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)
print('Accuracy for {} data: {:.4f}'.format(source, score))

Accuracy for imdb data: 0.8195

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
sentences=df['sentence']
y=df['label']
sentences_train, sentences_test, y_train, y_test = train_test_split(
   sentences, y, test_size=0.25, random_state=1000)
vectorizer = TfidfVectorizer()
vectorizer.fit(sentences_train)
X_train = vectorizer.transform(sentences_train)
X_test  = vectorizer.transform(sentences_test)
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
score = classifier.score(X_test, y_test)
print('Accuracy for {} data: {:.4f}'.format(source, score))

Accuracy for imdb data: 0.8195