In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('moviereviews.tsv', sep='\t')
df.head()

  label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [ ]:
from IPython.display import Markdown, display
display(Markdown(">>>"+"sdkjfff"))

>>>sdkjfff

In [ ]:
from IPython.display import Markdown, display
for i in range(5):
    display(Markdown('> '+df['review'][i]))
    print('--------------------------------------')

> how do films like mouse hunt get into theatres ?
isn't there a law or something ?
this diabolical load of claptrap from steven speilberg's dreamworks studio is hollywood family fare at its deadly worst .
mouse hunt takes the bare threads of a plot and tries to prop it up with overacting and flat-out stupid slapstick that makes comedies like jingle all the way look decent by comparison .
writer adam rifkin and director gore verbinski are the names chiefly responsible for this swill .
the plot , for what its worth , concerns two brothers ( nathan lane and an appalling lee evens ) who inherit a poorly run string factory and a seemingly worthless house from their eccentric father .
deciding to check out the long-abandoned house , they soon learn that it's worth a fortune and set about selling it in auction to the highest bidder .
but battling them at every turn is a very smart mouse , happy with his run-down little abode and wanting it to stay that way .
the story alternates between unfunny scenes of the brothers bickering over what to do with their inheritance and endless action sequences as the two take on their increasingly determined furry foe .
whatever promise the film starts with soon deteriorates into boring dialogue , terrible overacting , and increasingly uninspired slapstick that becomes all sound and fury , signifying nothing .
the script becomes so unspeakably bad that the best line poor lee evens can utter after another run in with the rodent is : " i hate that mouse " .
oh cringe !
this is home alone all over again , and ten times worse .
one touching scene early on is worth mentioning .
we follow the mouse through a maze of walls and pipes until he arrives at his makeshift abode somewhere in a wall .
he jumps into a tiny bed , pulls up a makeshift sheet and snuggles up to sleep , seemingly happy and just wanting to be left alone .
it's a magical little moment in an otherwise soulless film .
a message to speilberg : if you want dreamworks to be associated with some kind of artistic credibility , then either give all concerned in mouse hunt a swift kick up the arse or hire yourself some decent writers and directors .
this kind of rubbish will just not do at all .

--------------------------------------

> some talented actresses are blessed with a demonstrated wide acting range while others , almost as gifted , have more limited types of parts for which they are suitable .
as was amply evident after basic instinct , sharon stone can play sensual roles with great abandon .
rejecting her natural abilities , she has spent the rest of her entire career trying with little success to play against type .
gloria is her latest disaster .
babe ruth didn't quit baseball after one season to play football in a quixotic quest to prove his athletic dexterity , and neither should stone reject what she does best .
janeane garofalo , for example , is no less wonderful an actress because she could have never pulled off stone's part in basic instinct ; neither is stone any less talented because she couldn't do garofalo's comedic roles .
gloria , directed by respected director sidney lumet and adapted by steve antin from the 1980 screenplay by john cassavetes , was not screened in advance for critics , almost always a sign that the studio isn't behind the picture .
after seeing it in a nearly empty audience after it opened , it is clear why they held it from the press .
it is a film more to be endured than enjoyed .
as the story opens , an angry gloria ( stone ) is being released from prison after 3 years confinement .
she's got a bad attitude and a big mouth .
she also has a bad case of wavering and overblown new york accents , a disease suffered by much of the rest of the cast .
an annoying child actor named jean-luke figueroa plays a soon-to-be orphan named nicky .
just before his whole family is gunned down by hoods working for gloria's ex-boyfriend kevin ( jeremy northam ) , nicky's dad gives him a banana yellow floppy disk with secrets about kevin's operation and offers him a piece of fatherly advice .
 " be a man , " his father lectures him sternly .
 " don't trust nobody .
not no broads .
nobody . "
most of the film's leaden dialog is delivered with the emotive power of the automated time and temperature announcements .
add in the movie's almost non-existent background noise and the excruciatingly slow pacing , and you can hear the sounds of the lines falling to the ground like stones .
lumet places his actors in the frames like fruit in a still life painting .
they stand awkwardly mouthing the stiff sentences that pass for discourse .
 ( " say you're my baby , " kevin coos demandingly .
 " i'm not gonna , " gloria pouts back . )
the movie has a plethora of logical flaws and implausibilites .
the kid rarely seems the least bit worried or scared , no matter how many people are after him with guns , trying to kill him .
and in one key scene , the yellow floppy he holds is assumed to be the right disk without checking it and is further assumed never to have been copied .
gloria , who keeps saying how she hates kids , takes nicky under her wing and protects him from kevin and the bad guys .
think her maternal instincts will show up before the movie finally and predictably ends ?
if you don't know the answer , you may be just the right viewer for this film .
you have to say this for stone : she can keep a straight face .
when explaining life to a 7-year-old kid , she says with utter seriousness , " you got a lot of love making to make ; you got a lot of boozing to do . "
gloria runs 1 : 48 .
it is rated r for profanity , violence and brief male nudity and would be acceptable for teenagers .

--------------------------------------

> this has been an extraordinary year for australian films .
 " shine " has just scooped the pool at the australian film institute awards , picking up best film , best actor , best director etc . to that we can add the gritty " life " ( the anguish , courage and friendship of a group of male prisoners in the hiv-positive section of a jail ) and " love and other catastrophes " ( a low budget gem about straight and gay love on and near a university campus ) .
i can't recall a year in which such a rich and varied celluloid library was unleashed from australia .
 " shine " was one bookend .
stand by for the other one : " dead heart " .
>from the opening credits the theme of division is established .
the cast credits have clear and distinct lines separating their first and last names .
bryan | brown .
in a desert settlement , hundreds of kilometres from the nearest town , there is an uneasy calm between the local aboriginals and the handful of white settlers who live nearby .
the local police officer has the task of enforcing " white man's justice " to the aboriginals .
these are people with a proud 40 , 000 year heritage behind them .
naturally , this includes their own system of justice ; key to which is " payback " .
an eye for an eye .
revenge .
usually extracted by the spearing through of the recipient's thigh .
brown , as the officer , manages quite well to keep the balance .
he admits that he has to 'bend the rules' a bit , including actively encouraging at least one brutal " payback " .
 ( be warned that this scene , near the start , is not for the squeamish ) .
the local priest - an aboriginal , but in the " white fellas " church - has a foot on either side of the line .
he is , figuratively and literally , in both camps .
ernie dingo brings a great deal of understanding to this role as the man in the middle .
he is part churchman and part politician .
however the tension , like the heat , flies and dust , is always there .
whilst her husband - the local teacher - is in church , white lady kate ( milliken ) and her aborginal friend tony , ( pedersen ) have gone off into the hills .
he takes her to a sacred site , even today strictly men-only .
she appears to not know this .
tony tells her that this is a special place , an initiation place .
he then makes love to her , surrounded by ancient rock art .
the community finds out about this sacrilegious act and it's payback time .
the fuse is lit and the brittle inter-racial peace is shattered .
everyone is affected in the fall out .
to say more is to give away the details of this finely crafted film .
suffice to say it's a rewarding experience .
bryan brown , acting and co-producing , is the pivotal character .
his officer is real , human and therefore flawed .
brown comments that he expects audiences to feel warmth towards the man , then suddenly feel angry about him .
it wasn't long ago that i visited central australia - ayers rock ( uluru ) and alice springs - for the first time .
the wide-screen cinematography shows the dead heart of australia in a way that captures it's vicious beauty , but never deteriorates into a moving slide show , in which the gorgeous background dominates those pesky actors in the foreground .
the cultural clash has provided the thesis for many a film ; from the western to the birdcage .
at least three excellent australian films have covered the aboriginal people and the line between them and we anglo-saxon 'invaders' : " jedda " , " the chant of jimmie blacksmith " and " the last wave " .
in a year when the race 'debate' has reared up in australia , it is nourishing to see such an intelligent , non-judgemental film as " dead heart " .
the aboriginal priest best sums this up .
he is asked to say if he is a " black fella or white fella " .

--------------------------------------

> according to hollywood movies made in last few decades , life in small town is one of the worst things that could happen to a human being .
even worse fate awaits those who were unfortunate to grow up in those dark , god-forsaken places and later forced to live forever traumatised by the experience .
on the other hand , it seems that something more than atlantic ocean divides europe from america , because one of the most popular and beloved european films takes exactly the opposite view .
this film is amarcord , 1974 comedy by famous italian director federico fellini , which later gave inspiration to numerous imitations and homages , and even led few american screen artists to adopt its heretical views about benefits of small town life .
the film is based on the screenplay by fellini and tonino guerra and it lacks the plot in usual sense .
instead we follow one year in 1930s italian summer resort town of rimini through the series of short vignettes that depict various local events and customs , as well as series of local , often very colourful characters .
although many of those characters occasionally take the role of narrator , movie concentrates on its nominal protagonist , 14-year old boy titta ( played by bruno zanin ) and chronicles his sexual frustrations , obsession with local beauty queen named gradisca ( played by magali noel ) , problems in his lovingly dysfunctional family , as well as troubles his father ( played by armando brancia ) have with mussolini's fascist regime .
amarcord was often noted as the ultimate nostalgia film , and it probably explains why it is very popular , even among those people who actually don't like federico fellini's work very much .
every member of its potential audience would find part of himself or herself in this film , because fellini in this film clearly illustrates natural human desire to paint past in the best way possible .
distortion between actual past and its subjective interpretation could be found even in the title of the film - word " amarcord " is nothing more than badly pronounced phrase " i remember " in local italian dialect .
in the same way the word is distorted , so is the past in memories of those who remember it .
after the premiere , fellini rejected any claims about autobiographical character of this film , but it doesn't matter whether rimini of amarcord actually resembles rimini of fellini's childhood or not ; any place and any time could resemble characters and situations of this film .
fellini's views on nostalgia are clearly illustrated with a way he mixes reality and fantasy in this film .
even the most naturalistic scenes are laced with dark humour and grotesque images .
characters look like caricatures , actors playing them often deliberately overact , and women , especially those who fuel titta's sexual fantasies , often have certain body parts with gargantuan proportions .
every now and then , scenes that depict 1930s reality gradually slide into fantasies of movie's characters and rimini becomes almost indistinguishable from the magical place in characters' visions .
because of that , almost everything in this film looks different , and in most cases better , than it would have looked in the real life .
even the fascism gets fellinian make-over - fellini views mussolini's totalitarian regime as nothing more than visual spectacle ( explaining why similar regimes enjoyed such popular support throughout history ) and opportunity for comedy .
when fascists finally show their true colours and begin torturing their opponents , even this becomes opportunity for scenes of macabre humour .
unlike many of his italian colleagues in 1970s , who had used 1930s period setting to explicitly condemn fascism and serve fashionable political agenda , fellini doesn't care that much about politics .
lack of self-righteous moral perspective is compensated with fellini's humanistic approach to his characters .
each of them , regardless of age , gender , social class or physical appearance , is given opportunity to express his or her views , dreams and fears .
fellini treats all those characters with warmth and affection , even when he paints them as grotesque caricatures of real people .
because of this warmth and democratic spirit , amarcord could be viewed as one of the most humane films of 20th century , and it keeps its general feel good atmosphere despite depicting having many uncomfortable , melancholic and even tragic moments .
fellini couldn't produce such effects without using his own directorial talent that gave a very personal touch to this movie .
vignettes aren't memorable because of the characters only ; fellini uses camera , painting film in bright colours , especially in the scenes that depict character's fantasies .
fellini also knows how to use locations , whether such location happens to be luxurious hotel , bright-coloured beach or rural countryside .
even the down-to-earth streets of rimini , where everyone knows everyone , gets magical dimension during the snowfall .
on the other hand , lack of credible special effects somewhat diminished the same effect during the ocean liner scene .
this atmosphere is also provided by incredible talent of composer and fellini's long-time associate nino rota .
his amarcord theme is probably one of the most recognisable , most popular and most relaxing and uplifting pieces of film music ever produced .
that music alone should be the reason to view amarcord as one of the indisputable classics of seventh art .

--------------------------------------

> my first press screening of 1998 and already i've gotten a prime candidate for my worst ten of the year list .
what an auspicious beginning !
welcome to the dog days of winter when the only film openings of merit are those oscar contenders that the studios opened in late december in new york and l . a . and which are just now beginning to appear elsewhere .
firestorm , the directorial debut of dances with wolves's academy award winning cinematographer dean semler , is the first of the new year's crop of movies .
as our story opens , the movie pretentiously informs us that of the tens of thousands of firefighters only 400 are " smokejumpers . "
we then cut to a plane load of smoke jumping cowboys and one cowgirl , where one of the gung-ho guys is taking a romance quiz from " cosmopolitan . "
having the time of their lives , they then jump into the middle of a burning forest .
when , even in the beginning , the director can't get the small parts right , you can sense the movie is in trouble .
with the noisy fire roaring all about them and with the trapped people huddled near their gasoline-filled cars , smokejumper monica ( christianne hirt ) tells them to get away from their soon-to-explode vehicles .
not bothering to shout nor even get close to them , she announces her warning without raising her voice much or approaching the people .
miraculously , they manage to hear her and move away .
in a movie that specializes in cheap shots , the camera locates the proverbial young girl trapped in a nearby burning building .
as it does throughout , overly dramatic cinematographer stephen f . windon from the postman uses extremely fast zooms right down to the endangered girl's face .
our show's two heroes , the crew's chief , wynt perkins , played laconically by scott glenn , and his second-in-command , jesse graves , played by howie long in a weak attempt to be the next steven seagal , enter the burning house looking for the little girl .
in a panic they have difficulty in locating her before they are engulfed in flames .
the manipulative script has her hidden in her own dollhouse .
this mawkish show cuts back to monica , who has a life-or-death decision to make .
the chopper with the fire-retardant chemicals has only enough to save one group .
will it be the large group near the cars or the helpless little girl and monica's two firefighting buddies ?
she has only seconds to decide who will be saved .
yes , she goes for the majority , but , miracle of miracles , the other three come out alive anyway .
not content with a traditional firefighting story , chris soth's screenplay attempts to jazz it up by having william forsythe from palookaville play a vicious killer named randy earl shaye who sets a forest fire so that he can join the crew to put it out and then escape .
 ( " hoods in the woods , " is what the " ground-pounders " yell out when the convicts are bused in to help them fight the fire . )
along the way , shaye picks up an ornithologist hostage played by suzy amis , who turns out to have been trained in warrior ways by her father , who was a marine drill instructor .
most of the highly predictable movie is a long chase in which poor howie long is given one ridiculous stunt after another to look silly performing .
he flings a chain saw backwards over his head while riding a speeding motorcycle so that the saw can hit the windshield of the pursuing truck .
arguably the low point is when he escapes from a locked burning building by riding a motorcycle conveniently parked inside .
using a ramp , he shoots straight out of the top of the building's attic , and when he hits the ground , he just rides off in a cloud of dust .
when the film isn't using some stock footage of actual forest fires , the simulated ones look hokey .
editor jack hofstra cheapens the action even more by his use of burning flames in scene transitions .
the ending , with its sick twists , manages to be even worse than the rest of the movie .
perhaps the best that can be said for the picture is the faint praise i heard afterwards in the lobby , " it's not as bad as some of the television sitcoms . "
firestorm runs mercifully just 1 : 29 .
it is rated r for violence and language and would be acceptable for teenagers .

--------------------------------------

In [ ]:
df.shape

(2000, 2)

In [ ]:
len(df)

2000

In [ ]:
df.isnull().sum()

label      0
review    35
dtype: int64

In [ ]:
df.fillna(df["review"].mode()[0], inplace=True)

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

label     0
review    0
dtype: int64

| String     | `isspace()` |
| ---------- | ----------- |
| `" "`      | True        |
| `"     "`  | True        |
| `"\t"`     | True        |
| `"\n"`     | True        |
| `" \t\n "` | True        |
| `"Hello"`  | False       |
| `"Hello "` | False       |
| `""`       | False       |

In [ ]:
blanks = []

for idx,label,reviw in df.itertuples():
    if isinstance(label,str):
        if reviw.isspace() and reviw.strip()=="":
            blanks.append(idx)

print(len(blanks), 'blanks: ', blanks)

62 blanks:  [57, 71, 140, 147, 151, 208, 270, 283, 307, 313, 323, 334, 343, 351, 427, 448, 501, 522, 606, 633, 675, 696, 728, 738, 744, 786, 815, 820, 851, 866, 977, 986, 1072, 1079, 1156, 1204, 1260, 1272, 1294, 1299, 1314, 1330, 1332, 1426, 1455, 1456, 1486, 1493, 1525, 1531, 1538, 1568, 1584, 1588, 1600, 1662, 1763, 1851, 1904, 1905, 1908, 1993]

In [ ]:
df = df[df["review"].apply(
    lambda x: not (isinstance(x, str) and x.strip() == "")
)]
len(df)

1938

In [ ]:
# df.drop(blanks, inplace=True)
# len(df)

In [ ]:
df['label'].value_counts()

label
neg    969
pos    969
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X = df['review']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
y_train.value_counts() , y_test.value_counts()

(label
 neg    661
 pos    637
 Name: count, dtype: int64,
 label
 pos    332
 neg    308
 Name: count, dtype: int64)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

text_clf_nb = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', MultinomialNB()),])
text_clf_nb_cv = Pipeline([('cv', CountVectorizer()),
                     ('clf', MultinomialNB()),])

text_clf_lsvc = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),])
text_clf_lsvc_cv = Pipeline([('cv', CountVectorizer()),
                     ('clf', LinearSVC()),])

text_clf_nb.fit(X_train, y_train)
# text_clf_nb_cv.fit(X_train, y_train)
# text_clf_lsvc.fit(X_train, y_train)
# text_clf_lsvc_cv.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [ ]:
predictions = text_clf_nb.predict(X_test)

In [ ]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[287  21]
 [130 202]]

In [ ]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         neg       0.69      0.93      0.79       308
         pos       0.91      0.61      0.73       332

    accuracy                           0.76       640
   macro avg       0.80      0.77      0.76       640
weighted avg       0.80      0.76      0.76       640

In [ ]:
print(metrics.accuracy_score(y_test,predictions))

0.7640625

In [ ]:
text_clf_lsvc.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [ ]:
predictions = text_clf_lsvc.predict(X_test)

In [ ]:
print(metrics.confusion_matrix(y_test,predictions))

[[259  49]
 [ 49 283]]

In [ ]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         neg       0.84      0.84      0.84       308
         pos       0.85      0.85      0.85       332

    accuracy                           0.85       640
   macro avg       0.85      0.85      0.85       640
weighted avg       0.85      0.85      0.85       640

In [ ]:
print(metrics.accuracy_score(y_test,predictions))

0.846875

In [ ]:
text_clf_lsvc_cv.fit(X_train, y_train)
pred=text_clf_lsvc_cv.predict(X_test)
print(metrics.confusion_matrix(y_test,pred))
print(metrics.classification_report(y_test,pred))
print(metrics.accuracy_score(y_test,pred))
#

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[[259  49]
 [ 56 276]]
              precision    recall  f1-score   support

         neg       0.82      0.84      0.83       308
         pos       0.85      0.83      0.84       332

    accuracy                           0.84       640
   macro avg       0.84      0.84      0.84       640
weighted avg       0.84      0.84      0.84       640

0.8359375

In [ ]:
text_clf_nb_cv.fit(X_train, y_train)
pred=text_clf_lsvc_cv.predict(X_test)
print(metrics.confusion_matrix(y_test,pred))
print(metrics.classification_report(y_test,pred))
print(metrics.accuracy_score(y_test,pred))
#

[[259  49]
 [ 56 276]]
              precision    recall  f1-score   support

         neg       0.82      0.84      0.83       308
         pos       0.85      0.83      0.84       332

    accuracy                           0.84       640
   macro avg       0.84      0.84      0.84       640
weighted avg       0.84      0.84      0.84       640

0.8359375